apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  user: xxx==                    # encoded in base64
  password: xxx==                # encoded in base64
  gwid: xxx==                    # encoded in base64


